name: MAUI Prueba

on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
        
jobs:        
  build-android:
    name: "Build Android"
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui
          dotnet workload install android
      - name: Restore Dependencies
        run: dotnet restore ./PruebaMaui/PruebaMaui/PruebaMaui.csproj
      - name: Build Android
        run: dotnet build ./PruebaMaui/PruebaMaui/PruebaMaui.csproj  -c Release -f net8.0-android --no-restore
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PruebaMai-Android
          path: ./PruebaMaui/PruebaMaui/bin/Release/net8.0-android/*Signed.a*
          
  build-windows:
    name: "Build Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workloads
        run: dotnet workload install maui
      - name: Restore Dependencies
        run: dotnet restore ./PruebaMaui/PruebaMaui/PruebaMaui.csproj
      - name: Build Windows
        run: dotnet build ./PruebaMaui/PruebaMaui/PruebaMaui.csproj -c Release -f net8.0-windows --no-restore
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PruebaMaui-Windows
          path: ./PruebaMaui/PruebaMaui/bin/Release/net8.0-windows*/**/PruebaMaui*.msix   

  build-ios:
    name: "Build iOS"
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui
          dotnet workload install ios
      - name: Restore Dependencies
        run: dotnet restore ./PruebaMaui/PruebaMaui/PruebaMaui.csproj
      - name: Build iOS
        run: dotnet build ./PruebaMaui/PruebaMaui/PruebaMaui.csproj -c Release -f net8.0-ios --no-restore
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PruebaMaui-iOS
          path: ./PruebaMaui/PruebaMaui/bin/Release/net8.0-ios/**/*.app/
          
  build-maccatalyst:
    name: "Build MacCatalyst"
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui
          dotnet workload install maccatalyst
      - name: Restore Dependencies
        run: dotnet restore ./PruebaMaui/PruebaMaui/PruebaMaui/PruebaMaui.csproj
      - name: Build MacCatalyst
        run: dotnet build ./PruebaMaui/PruebaMaui/PruebaMaui.csproj -c Release -f net8.0-maccatalyst --no-restore
      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PruebaMai-MacCatalyst
          path: ./PruebaMai/PruebaMaui/bin/Release/net8.0-maccatalyst/**/*.app/
